#Application.properties file

spring.application.name=resumebuilderapi

#MongoDb configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port=${PORT:8080}


# Email Configuration (Gmail SMTP)
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${SPRING_MAIL_FROM}


# Application info
app.base.url=${APP_BASE_URL:http://localhost:8080}

#Claudinary configuration

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

#Razorpay configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# Set max file size to 10MB
server.tomcat.max-swallow-size=-1
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB